### PR TITLE
Update to 1.2.2

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
@conda-forge-admin osx build for Python 3.9 is failing due to conda conflicts in creation of the host environment. 

Could you please suggest a way to resolve it? I assume this workflow is required for the merge. Let me know otherwise.

**Comment by oleksandr-pavlyk** [comment]
@conda-forge-bot rerender

**Comment by oleksandr-pavlyk** [comment]
@isuruf Can you please point me in the right direction. It appears the problem with OSX Py=3.9 is that the recipe is pulling NumPy 1.16 into build requirement, which is not available for Py=3.9

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by oleksandr-pavlyk** [comment]
Thank you @isuruf

**Pull request merged**
